services:
    app:
      container_name: nestjs-project1
      image: nestjs-image1
      build:
         context: .
      ports:
      - "3000:3000"
      env_file: .env
      restart: always
    
  